## Chapter 5
---

In [1]:
x <- 1

In [2]:
x

[1] 1

In [3]:
print(x)

[1] 1


In [4]:
msg <- "Hello World"

In [5]:
msg

[1] "Hello World"

In [6]:
x <- 

ERROR: Error in parse(text = x, srcfile = src): <text>:2:0: unexpected end of input
1: x <- 
   ^


In [7]:
# invalid expression

*an integer sequence*

In [8]:
x <- 1:20

In [9]:
x

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [11]:
# numeric object
x <- 1
x

[1] 1

In [12]:
# integer object
x <- 1L
x

[1] 1

In [14]:
# Infinity
Inf

[1] Inf

In [15]:
# not a number
NaN

[1] NaN

In [16]:
# null
NULL

NULL

In [17]:
attributes(x)

NULL

In [18]:
attributes("Hello")

NULL

### Vectors

In [19]:
# numric vector
c(0.5, 1.3)

[1] 0.5 1.3

In [21]:
# boolean vector
c(TRUE, FALSE)

[1]  TRUE FALSE

In [22]:
c(T, F)

[1]  TRUE FALSE

In [23]:
# characters
c("a", "b", "c")

[1] "a" "b" "c"

In [24]:
# integer
c(1L, 3L)

[1] 1 3

In [25]:
# or integer range
1:6

[1] 1 2 3 4 5 6

In [26]:
# complex
c(1+0i, 2+3i)

[1] 1+0i 2+3i

In [28]:
# initialize vector
vector("numeric", length=3)

[1] 0 0 0

In [29]:
vector("integer", length=3)

[1] 0 0 0

*only same classes are allowed in a vector*

In [30]:
c(2, "a")

[1] "2" "a"

In [31]:
c(T, 3)

[1] 1 3

### Coercion

In [32]:
x <- 4

In [33]:
class(x)

[1] "numeric"

In [34]:
x <- 0:4

In [35]:
class(x)

[1] "integer"

In [36]:
as.numeric(x)

[1] 0 1 2 3 4

In [37]:
as.logical(x)

[1] FALSE  TRUE  TRUE  TRUE  TRUE

In [38]:
as.character(x)

[1] "0" "1" "2" "3" "4"

*invalid coercion*

In [39]:
x <- c("a", "b")
as.integer(x)

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”

[1] NA NA

In [40]:
as.logical(x)

[1] NA NA

In [41]:
attributes(x)

NULL

### Matrices

In [42]:
m <- matrix(nrow=2, ncol=3)
m

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

In [43]:
attributes(m)

$dim
[1] 2 3

In [44]:
dim(m)

[1] 2 3

In [45]:
class(m)

[1] "matrix"

In [46]:
class(dim(m))

[1] "integer"

In [49]:
m <- matrix(1:6, ncol=2, nrow=3)
m

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [51]:
m <- matrix(1:6, nrow=2, ncol=3)
m

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [56]:
m <- 1:10

In [57]:
m

[1]  1  2  3  4  5  6  7  8  9 10

In [58]:
dim(m) <- c(2, 5)

In [59]:
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

**column-binding and row-binding**

In [60]:
x <- 1:3
y <- 10:12

In [61]:
x

[1] 1 2 3

In [62]:
y

[1] 10 11 12

In [63]:
cbind(x, y)

x y 
[1,] 1 10
[2,] 2 11
[3,] 3 12

In [64]:
rbind(x, y)

[,1] [,2] [,3]
x  1    2    3  
y 10   11   12

### Lists

- are special type of vector that can contain different classes

In [65]:
x <- list("a", 1, T)

In [66]:
x

[[1]]
[1] "a"

[[2]]
[1] 1

[[3]]
[1] TRUE

In [67]:
attributes(x)

NULL

In [68]:
vector("list", length=3)

[[1]]
NULL

[[2]]
NULL

[[3]]
NULL

### Factors

- are used to represent categorical data and can be ordered or unordered

In [69]:
x <- factor(c("yes", "no", "yes", "no", "yes", "yes"))

In [70]:
x

[1] yes no  yes no  yes yes
Levels: no yes

In [71]:
attributes(x)

$levels
[1] "no"  "yes"

$class
[1] "factor"

In [72]:
levels(x)

[1] "no"  "yes"

In [73]:
class(x)

[1] "factor"

In [74]:
table(x)

x
 no yes 
  2   4 

In [75]:
unclass(x)

[1] 2 1 2 1 2 2
attr(,"levels")
[1] "no"  "yes"

In [77]:
attr(x, "levels")

[1] "no"  "yes"

In [78]:
x <- factor(c("yes", "no", "yes"), levels=c("yes", "no"))

In [79]:
x

[1] yes no  yes
Levels: yes no

### Missing values

In [80]:
x <- c(1, 2, NA, 3, 4)

In [81]:
is.na(x)

[1] FALSE FALSE  TRUE FALSE FALSE

In [82]:
is.nan(x)

[1] FALSE FALSE FALSE FALSE FALSE

In [83]:
y <- c(1, 2, 3, NaN)

In [84]:
is.na(y)

[1] FALSE FALSE FALSE  TRUE

In [85]:
is.nan(y)

[1] FALSE FALSE FALSE  TRUE

### Data Frames

In [86]:
x <- data.frame(foo=1:4, bar=c(T, F, T, T))

In [87]:
x

foo bar  
1 1    TRUE
2 2   FALSE
3 3    TRUE
4 4    TRUE

In [88]:
attributes(x)

$names
[1] "foo" "bar"

$class
[1] "data.frame"

$row.names
[1] 1 2 3 4

In [89]:
names(x)

[1] "foo" "bar"

In [90]:
row.names(x)

[1] "1" "2" "3" "4"

In [91]:
nrow(x)

[1] 4

In [92]:
ncol(x)

[1] 2

### Names

In [93]:
temp <- c(10.3, 15.6, 11.2)

In [94]:
names(temp)

NULL

In [95]:
names(temp) <- c("Kathmandu", "Pokhara", "Birtamod")

In [96]:
names(temp)

[1] "Kathmandu" "Pokhara"   "Birtamod"

In [97]:
temp

Kathmandu   Pokhara  Birtamod 
     10.3      15.6      11.2

In [101]:
y <- list(first=12, second=34, third=67)

In [102]:
y

$first
[1] 12

$second
[1] 34

$third
[1] 67

In [108]:
y["first"]

$first
[1] 12

In [109]:
temp["Kathmandu"]

Kathmandu 
     10.3

*matrices*

In [110]:
m <- matrix(1:4, nrow=2, ncol=2)

In [111]:
m

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [112]:
dimnames(m) <- list(c("a", "b"), c("c", "d"))

In [113]:
m

c d
a 1 3
b 2 4

In [114]:
colnames(m) <- c("p", "q")

In [115]:
m

p q
a 1 3
b 2 4

In [116]:
rownames(m) <- c("x", "y")

In [117]:
m

p q
x 1 3
y 2 4

*data frames*

In [118]:
d = data.frame(foo=1:4, bar=c(T, F, T, F))

In [119]:
d

foo bar  
1 1    TRUE
2 2   FALSE
3 3    TRUE
4 4   FALSE

In [120]:
names(d) <- c("Foo", "Bar")

In [121]:
d

Foo Bar  
1 1    TRUE
2 2   FALSE
3 3    TRUE
4 4   FALSE

In [122]:
row.names(d) <- c("A", "B", "C", "D")

In [123]:
d

Foo Bar  
A 1    TRUE
B 2   FALSE
C 3    TRUE
D 4   FALSE

## Chapter 6
---